// <auto-generated />
using System;
using EnvironmentalAudit.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EnvironmentalAudit.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260826182916_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EnvironmentalAudit.Api.Models.Audit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FacilityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Responsible")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Audits");
                });

            modelBuilder.Entity("EnvironmentalAudit.Api.Models.AuditData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuditId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DieselLiters")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ElectricityKwh")
                        .HasColumnType("numeric");

                    b.Property<decimal>("GasolineLiters")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HazardousWasteKg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NaturalGasM3")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NonHazardousWasteKg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("RecycledWasteKg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("WasteWaterM3")
                        .HasColumnType("numeric");

                    b.Property<decimal>("WaterUsedM3")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AuditId")
                        .IsUnique();

                    b.ToTable("AuditData");
                });

            modelBuilder.Entity("EnvironmentalAudit.Api.Models.AuditResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuditId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("EmissionsScore")
                        .HasColumnType("numeric");

                    b.Property<decimal>("EnergyScore")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OverallScore")
                        .HasColumnType("numeric");

                    b.Property<decimal>("RecyclingRate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalEmissions")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalWaste")
                        .HasColumnType("numeric");

                    b.Property<decimal>("WasteScore")
                        .HasColumnType("numeric");

                    b.Property<decimal>("WaterScore")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AuditId")
                        .IsUnique();

                    b.ToTable("AuditResults");
                });

            modelBuilder.Entity("EnvironmentalAudit.Api.Models.AuditData", b =>
                {
                    b.HasOne("EnvironmentalAudit.Api.Models.Audit", "Audit")
                        .WithOne("Data")
                        .HasForeignKey("EnvironmentalAudit.Api.Models.AuditData", "AuditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Audit");
                });

            modelBuilder.Entity("EnvironmentalAudit.Api.Models.AuditResult", b =>
                {
                    b.HasOne("EnvironmentalAudit.Api.Models.Audit", "Audit")
                        .WithOne("Result")
                        .HasForeignKey("EnvironmentalAudit.Api.Models.AuditResult", "AuditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Audit");
                });

            modelBuilder.Entity("EnvironmentalAudit.Api.Models.Audit", b =>
                {
                    b.Navigation("Data");

                    b.Navigation("Result");
                });
#pragma warning restore 612, 618
        }
    }
}
